# Generated by Django 3.2 on 2022-04-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
