# Generated by Django 3.2 on 2022-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productslider',
            name='product',
            field=models.ManyToManyField(related_name='productslider', to='product.Product'),
        ),
    ]
